In [1]:
# Imports:
import numpy as np
import pandas as pd

#from model_output_eval import cosine_similarity_score, rouge_similarity_score, in_out_correlation_score
from model_output_eval import load_complete_split_reddit_data, load_limited_split_data
from model_output_eval import model_collect_scores

c:\Users\trothe\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### Bare Dataset - Complete

In [2]:
train_art_df, val_art_df, train_tld_cmt_df, val_tld_cmt_df = load_complete_split_reddit_data("cmtsplit")

reference_comment_df = train_tld_cmt_df
generated_comment_df = val_tld_cmt_df

complete_dataset_score_dict = model_collect_scores(gen_cmt_df=generated_comment_df, ref_cmt_df=reference_comment_df)

Found 216 article ids in generated comments and 217 article ids in reference comments
Sentence embedding length> 768


Training epochs:   0%|          | 0/3 [00:00<?, ?it/s]

Running epoch: 1


Training epochs:  33%|███▎      | 1/3 [00:06<00:13,  6.96s/it]

Loss for this epoch: 5.32204069466976
Running epoch: 2


Training epochs:  67%|██████▋   | 2/3 [00:13<00:06,  6.99s/it]

Loss for this epoch: 5.27530677122658
Running epoch: 3


Training epochs: 100%|██████████| 3/3 [00:21<00:00,  7.00s/it]


Loss for this epoch: 5.252282387532896


Evaluation batches: 100%|██████████| 335/335 [00:00<00:00, 3617.23it/s]

Average evaluation loss: 5.2503146854799185
Classification accuracy: 0.13880597054958344
[tensor(0, dtype=torch.int32), tensor(1, dtype=torch.int32), tensor(1, dtype=torch.int32), tensor(1, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(3, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, 

tensor(0.1388)
======= DONE WITH SBERT CLASSIFICATION ======== 


Batches: 100%|██████████| 2/2 [00:00<00:00,  2.98it/s]


tensor([0, 1, 4])


### Bare Dataset - Limited

In [2]:
train_art_df, val_art_df, train_tld_cmt_df, val_tld_cmt_df = load_limited_split_data("cmtsplit")

reference_comment_df = train_tld_cmt_df
generated_comment_df = val_tld_cmt_df

limited_dataset_score_dict = model_collect_scores(gen_cmt_df=generated_comment_df, ref_cmt_df=reference_comment_df)

Found 10 article ids in generated comments and 10 article ids in reference comments
Sentence embedding length> 768


Training epochs:   0%|          | 0/12 [00:00<?, ?it/s]

Running epoch: 1


c:\Users\trothe\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\functional.py:1956: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


Loss for this epoch: 2.2203495264053346
Running epoch: 2


Training epochs:  17%|█▋        | 2/12 [00:00<00:00, 13.44it/s]

Loss for this epoch: 1.8832735061645507
Running epoch: 3


Loss for this epoch: 1.4970733761787414
Running epoch: 4


Training epochs:  33%|███▎      | 4/12 [00:00<00:00, 15.09it/s]

Loss for this epoch: 1.1644610613584518
Running epoch: 5


Loss for this epoch: 0.9183677911758423
Running epoch: 6


Training epochs:  50%|█████     | 6/12 [00:00<00:00, 15.56it/s]

Loss for this epoch: 0.7425308853387833
Running epoch: 7


Loss for this epoch: 0.6147273913025856
Running epoch: 8


Training epochs:  67%|██████▋   | 8/12 [00:00<00:00, 16.22it/s]

Loss for this epoch: 0.5135120809078216
Running epoch: 9


Loss for this epoch: 0.4169078655540943
Running epoch: 10


Training epochs:  83%|████████▎ | 10/12 [00:00<00:00, 16.87it/s]

Loss for this epoch: 0.3411408193409443
Running epoch: 11


Loss for this epoch: 0.2788225427269936
Running epoch: 12


Training epochs: 100%|██████████| 12/12 [00:00<00:00, 15.90it/s]


Loss for this epoch: 0.22133319154381753


Evaluation batches: 100%|██████████| 10/10 [00:00<00:00, 1250.65it/s]


Average evaluation loss: 1.1549452811479568
Classification accuracy: 0.5945945978164673
[tensor(0, dtype=torch.int32), tensor(0, dtype=torch.int32), tensor(0, dtype=torch.int32), tensor(0, dtype=torch.int32), tensor(0, dtype=torch.int32), tensor(0, dtype=torch.int32), tensor(0, dtype=torch.int32), tensor(0, dtype=torch.int32), tensor(0, dtype=torch.int32), tensor(0, dtype=torch.int32), tensor(0, dtype=torch.int32), tensor(0, dtype=torch.int32), tensor(0, dtype=torch.int32), tensor(1, dtype=torch.int32), tensor(1, dtype=torch.int32), tensor(1, dtype=torch.int32), tensor(1, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, d

Batches: 100%|██████████| 5/5 [00:07<00:00,  1.55s/it]


SVM accuracy:  0.5743243243243243
======= DONE WITH SBERT CLASSIFICATION ======== 


Batches: 100%|██████████| 1/1 [00:00<00:00,  1.54it/s]


Mean cosine similarity score over all articles:  0.5200868
0.08278833291915662 0.025573602235350736
0.1890138896283346 0.050279767960327876
0.14225566371475593 0.04167192882039931
0.13976245703473367 0.05051120501126017
0.15791725103687093 0.031019285750303254
0.16625553553570743 0.045345438157147304
0.06654906129922356 0.024769217704930523
0.1325535806464298 0.02349359814432227
0.09918295987924736 0.012195120846966192
0.15522200190803082 0.05754295719427719
Mean Rouge-1 score over all articles:  0.13315007336024906
Worst Rouge-1 score over all articles:  0.06654906129922356
Mean Rouge-2 score over all articles:  0.03624021218252848
Worst Rouge-2 score over all articles:  0.012195120846966192
Found 10 article ids in generated comments and 10 article ids in reference comments


Batches: 100%|██████████| 10/10 [00:01<00:00,  8.29it/s]


0.581081081081081
              precision    recall  f1-score   support

           0       0.63      0.92      0.75        13
           1       0.36      1.00      0.53         4
           2       0.62      0.43      0.51        30
           3       0.50      0.35      0.42        31
           4       0.60      0.67      0.63         9
           5       1.00      0.60      0.75        20
           6       0.31      0.50      0.38         8
           7       0.57      0.80      0.67        10
           8       0.33      0.75      0.46         4
           9       0.76      0.68      0.72        19

    accuracy                           0.58       148
   macro avg       0.57      0.67      0.58       148
weighted avg       0.63      0.58      0.58       148

[[12  0  0  0  0  0  0  1  0  0]
 [ 0  4  0  0  0  0  0  0  0  0]
 [ 1  0 13  8  1  0  1  2  2  2]
 [ 3  0  8 11  3  0  2  3  0  1]
 [ 1  0  0  1  6  0  0  0  1  0]
 [ 0  2  0  1  0 12  3  0  1  1]
 [ 2  2  0  0  0  0  4  0

In [4]:
limited_dataset_score_dict["sbert_class_accuracy"]

tensor(0.5405)

### GPT-4 test - cmtsplit

In [3]:
# Data import; Should at least have the columns: "article_id", "body", "level"
# other columns will be ignored
train_art_df, val_art_df, train_tld_cmt_df, val_tld_cmt_df =  load_limited_split_data("cmtsplit")

reference_comment_df = val_tld_cmt_df
generated_comment_df = pd.read_csv("S:\\Sync\\University\\2023_MRP_1\\MRP1_WorkDir\\data\\destilled\\cmtsplit\\r_cmtsplit_generated_[gpt-4]_[withexamples]_[T=0.8].csv", sep=";")

gpt4_scores_dict = model_collect_scores(gen_cmt_df=generated_comment_df, ref_cmt_df=reference_comment_df)


Found 10 article ids in generated comments and 10 article ids in reference comments
Sentence embedding length> 768


Training epochs:   0%|          | 0/12 [00:00<?, ?it/s]

Running epoch: 1


c:\Users\trothe\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\functional.py:1956: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


Loss for this epoch: 2.229871368408203
Running epoch: 2


Loss for this epoch: 1.961147129535675
Running epoch: 3


Training epochs:  25%|██▌       | 3/12 [00:00<00:00, 29.36it/s]

Loss for this epoch: 1.7196582913398744
Running epoch: 4


Loss for this epoch: 1.51458979845047
Running epoch: 5


Loss for this epoch: 1.317033588886261
Running epoch: 6


Loss for this epoch: 1.0974879026412965
Running epoch: 7


Training epochs:  58%|█████▊    | 7/12 [00:00<00:00, 30.00it/s]

Loss for this epoch: 0.9175463378429413
Running epoch: 8


Loss for this epoch: 0.7320262640714645
Running epoch: 9


Loss for this epoch: 0.6620064496994018
Running epoch: 10


Loss for this epoch: 0.520003592967987
Running epoch: 11


Training epochs:  92%|█████████▏| 11/12 [00:00<00:00, 31.88it/s]

Loss for this epoch: 0.4365940153598785
Running epoch: 12


Training epochs: 100%|██████████| 12/12 [00:00<00:00, 31.41it/s]


Loss for this epoch: 0.3856943815946579


Evaluation batches: 100%|██████████| 20/20 [00:00<00:00, 2000.19it/s]


Average evaluation loss: 1.1632683597505094
Classification accuracy: 0.640625
[tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch

Batches: 100%|██████████| 10/10 [00:03<00:00,  2.64it/s]


SVM accuracy:  0.609375
======= DONE WITH SBERT CLASSIFICATION ======== 


Batches: 100%|██████████| 1/1 [00:00<00:00, 17.37it/s]


Mean cosine similarity score over all articles:  0.5426458
0.08797747483748133 0.019106662846578228
0.12042956617063366 0.002790178317527881
0.18869633677443326 0.06467058751335705
0.08949023909671121 0.017588887770821005
0.11860502643732838 0.05906936323845556
0.09754788298308761 0.027487268379791006
0.14536318237343918 0.04821820623227054
0.17517402291962111 0.060039722185970194
0.10867150627164054 0.023120350898857295
0.08413040718893075 0.01363469065628771
Mean Rouge-1 score over all articles:  0.12160856450533072
Worst Rouge-1 score over all articles:  0.08413040718893075
Mean Rouge-2 score over all articles:  0.03357259180399164
Worst Rouge-2 score over all articles:  0.002790178317527881
Found 10 article ids in generated comments and 10 article ids in reference comments


Batches: 100%|██████████| 5/5 [00:00<00:00,  6.12it/s]


0.609375
              precision    recall  f1-score   support

           0       1.00      0.56      0.72        32
           1       1.00      0.31      0.48        32
           2       0.35      0.97      0.51        32
           3       0.30      0.53      0.39        32
           4       0.90      0.88      0.89        32
           5       0.91      0.94      0.92        32
           6       0.88      0.22      0.35        32
           7       0.96      0.78      0.86        32
           8       0.00      0.00      0.00        32
           9       0.60      0.91      0.72        32

    accuracy                           0.61       320
   macro avg       0.69      0.61      0.58       320
weighted avg       0.69      0.61      0.58       320

[[18  0  3 11  0  0  0  0  0  0]
 [ 0 10  4  1  1  2  1  0  1 12]
 [ 0  0 31  1  0  0  0  0  0  0]
 [ 0  0 14 17  1  0  0  0  0  0]
 [ 0  0  3  1 28  0  0  0  0  0]
 [ 0  0  2  0  0 30  0  0  0  0]
 [ 0  0  7 15  0  0  7  0  0  3]
 

### GPT-3.5-Turbo test - cmtsplit

In [4]:
# Data import; Should at least have the columns: "article_id", "body", "level"
# other columns will be ignored
train_art_df, val_art_df, train_tld_cmt_df, val_tld_cmt_df =  load_limited_split_data("cmtsplit")

reference_comment_df = val_tld_cmt_df
generated_comment_df = pd.read_csv("S:\\Sync\\University\\2023_MRP_1\\MRP1_WorkDir\\data\\destilled\\cmtsplit\\r_cmtsplit_generated_[gpt-3.5-turbo]_[with32examples]_[T=0.8].csv", sep=";")

gpt35turbo_scores_dict = model_collect_scores(gen_cmt_df=generated_comment_df, ref_cmt_df=reference_comment_df)


Found 10 article ids in generated comments and 10 article ids in reference comments
Sentence embedding length> 768


Training epochs:   0%|          | 0/12 [00:00<?, ?it/s]

Running epoch: 1


c:\Users\trothe\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\functional.py:1956: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


Loss for this epoch: 2.23606960773468
Running epoch: 2


Loss for this epoch: 1.9795202016830444
Running epoch: 3


Loss for this epoch: 1.746719980239868
Running epoch: 4


Training epochs:  33%|███▎      | 4/12 [00:00<00:00, 35.23it/s]

Loss for this epoch: 1.476270365715027
Running epoch: 5


Loss for this epoch: 1.2609840095043183
Running epoch: 6


Loss for this epoch: 1.0529296934604644
Running epoch: 7


Loss for this epoch: 0.9280294954776764
Running epoch: 8


Training epochs:  67%|██████▋   | 8/12 [00:00<00:00, 35.23it/s]

Loss for this epoch: 0.7725303649902344
Running epoch: 9


Loss for this epoch: 0.6408800512552262
Running epoch: 10


Loss for this epoch: 0.5545343637466431
Running epoch: 11


Loss for this epoch: 0.45079657435417175
Running epoch: 12


Training epochs: 100%|██████████| 12/12 [00:00<00:00, 35.32it/s]


Loss for this epoch: 0.3761537030339241


Evaluation batches: 100%|██████████| 20/20 [00:00<00:00, 2221.97it/s]


Average evaluation loss: 1.1501799749210477
Classification accuracy: 0.6499999761581421
[tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, d

Batches: 100%|██████████| 10/10 [00:05<00:00,  1.97it/s]


SVM accuracy:  0.640625
======= DONE WITH SBERT CLASSIFICATION ======== 


Batches: 100%|██████████| 1/1 [00:00<00:00, 17.23it/s]


Mean cosine similarity score over all articles:  0.5269474
0.14354135806434082 0.022592909488752234
0.12016388845447203 0.00322712389016974
0.1661836793353153 0.05134098585227516
0.09840725554993673 0.026156855060078726
0.15731388311508968 0.06568250892922305
0.0924896465264326 0.027474068557281843
0.1357850003023231 0.04923290817006239
0.2233054453583682 0.0831065774428479
0.10550521884542763 0.010437493553262796
0.1180596371491629 0.019834597603439266
Mean Rouge-1 score over all articles:  0.13607550127008688
Worst Rouge-1 score over all articles:  0.0924896465264326
Mean Rouge-2 score over all articles:  0.035908602854739305
Worst Rouge-2 score over all articles:  0.00322712389016974
Found 10 article ids in generated comments and 10 article ids in reference comments


Batches: 100%|██████████| 5/5 [00:00<00:00,  6.19it/s]


0.640625
              precision    recall  f1-score   support

           0       0.97      0.88      0.92        32
           1       1.00      0.19      0.32        32
           2       0.35      0.94      0.51        32
           3       0.46      0.53      0.49        32
           4       0.90      0.81      0.85        32
           5       0.65      0.97      0.78        32
           6       0.94      0.50      0.65        32
           7       1.00      0.75      0.86        32
           8       1.00      0.06      0.12        32
           9       0.58      0.78      0.67        32

    accuracy                           0.64       320
   macro avg       0.78      0.64      0.62       320
weighted avg       0.78      0.64      0.62       320

[[28  0  1  1  0  1  0  0  0  1]
 [ 0  6  7  4  1  7  0  0  0  7]
 [ 0  0 30  1  0  1  0  0  0  0]
 [ 0  0 13 17  1  1  0  0  0  0]
 [ 0  0  3  1 26  0  0  0  0  2]
 [ 0  0  0  1  0 31  0  0  0  0]
 [ 0  0  6  4  0  4 16  0  0  2]
 

### GPT-3.5-Davinci-003 test - cmtsplit

In [5]:
# Data import; Should at least have the columns: "article_id", "body", "level"
# other columns will be ignored
train_art_df, val_art_df, train_tld_cmt_df, val_tld_cmt_df =  load_limited_split_data("cmtsplit")

reference_comment_df = val_tld_cmt_df
generated_comment_df = pd.read_csv("S:\\Sync\\University\\2023_MRP_1\\MRP1_WorkDir\\data\\destilled\\cmtsplit\\r_cmtsplit_generated_[text-davinci-003]_[with32examples]_[T=0.8].csv", sep=";")

gpt35davinci_scores_dict = model_collect_scores(gen_cmt_df=generated_comment_df, ref_cmt_df=reference_comment_df)

Found 10 article ids in generated comments and 10 article ids in reference comments
Sentence embedding length> 768


Training epochs:   0%|          | 0/12 [00:00<?, ?it/s]

Running epoch: 1


c:\Users\trothe\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\functional.py:1956: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


Loss for this epoch: 2.2415940523147584
Running epoch: 2


Loss for this epoch: 1.974646306037903
Running epoch: 3


Loss for this epoch: 1.7700504660606384
Running epoch: 4


Training epochs:  33%|███▎      | 4/12 [00:00<00:00, 34.07it/s]

Loss for this epoch: 1.5326216697692872
Running epoch: 5


Loss for this epoch: 1.3094439268112184
Running epoch: 6


Loss for this epoch: 1.0845414340496062
Running epoch: 7


Loss for this epoch: 0.9432069420814514
Running epoch: 8


Training epochs:  67%|██████▋   | 8/12 [00:00<00:00, 34.05it/s]

Loss for this epoch: 0.7557481318712235
Running epoch: 9


Loss for this epoch: 0.655122971534729
Running epoch: 10


Loss for this epoch: 0.5373095870018005
Running epoch: 11


Loss for this epoch: 0.453631716966629
Running epoch: 12


Training epochs: 100%|██████████| 12/12 [00:00<00:00, 33.57it/s]


Loss for this epoch: 0.3944047033786774


Evaluation batches: 100%|██████████| 20/20 [00:00<00:00, 2494.90it/s]


Average evaluation loss: 1.128603196144104
Classification accuracy: 0.6499999761581421
[tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dt

Batches: 100%|██████████| 10/10 [00:06<00:00,  1.46it/s]


SVM accuracy:  0.63125
======= DONE WITH SBERT CLASSIFICATION ======== 


Batches: 100%|██████████| 1/1 [00:00<00:00, 17.64it/s]


Mean cosine similarity score over all articles:  0.5375775
0.17705163183312267 0.036546721600871
0.15359963912618824 0.004265200044889715
0.18119794553720325 0.048939426141049264
0.12381407919436474 0.021691098687550155
0.15136534359799067 0.04208693490022466
0.0999107122591967 0.02577183657677224
0.1824308059388734 0.04739899372044345
0.20081112172288734 0.06525228416306568
0.131004180172183 0.022122487379557625
0.12173833302542358 0.013263703060091806
Mean Rouge-1 score over all articles:  0.15229237924074335
Worst Rouge-1 score over all articles:  0.0999107122591967
Mean Rouge-2 score over all articles:  0.032733868627451555
Worst Rouge-2 score over all articles:  0.004265200044889715
Found 10 article ids in generated comments and 10 article ids in reference comments


Batches: 100%|██████████| 5/5 [00:00<00:00,  6.21it/s]


0.553125
              precision    recall  f1-score   support

           0       1.00      0.88      0.93        32
           1       1.00      0.25      0.40        32
           2       0.23      1.00      0.38        32
           3       0.17      0.03      0.05        32
           4       0.92      0.72      0.81        32
           5       0.97      0.88      0.92        32
           6       0.60      0.09      0.16        32
           7       1.00      0.88      0.93        32
           8       1.00      0.03      0.06        32
           9       0.48      0.78      0.60        32

    accuracy                           0.55       320
   macro avg       0.74      0.55      0.52       320
weighted avg       0.74      0.55      0.52       320

[[28  0  4  0  0  0  0  0  0  0]
 [ 0  8  4  2  1  0  2  0  0 15]
 [ 0  0 32  0  0  0  0  0  0  0]
 [ 0  0 29  1  1  1  0  0  0  0]
 [ 0  0  9  0 23  0  0  0  0  0]
 [ 0  0  2  0  0 28  0  0  0  2]
 [ 0  0 21  1  0  0  3  0  0  7]
 

### Godel-v1.1 test - cmtsplit (complete)

In [6]:
# Data import; Should at least have the columns: "article_id", "body", "level"
# other columns will be ignored
#train_art_df, val_art_df, train_tld_cmt_df, val_tld_cmt_df = load_complete_split_reddit_data("cmtsplit")
train_art_df, val_art_df, train_tld_cmt_df, val_tld_cmt_df =  load_limited_split_data("cmtsplit")

reference_comment_df = val_tld_cmt_df
generated_comment_df = pd.read_csv("S:\\Sync\\University\\2023_MRP_1\\MRP1_WorkDir\\data\\destilled\\cmtsplit\\init_godel_cmtsplit_limited_generated_comments.csv", sep=";")

godel_scores_dict = model_collect_scores(gen_cmt_df=generated_comment_df, ref_cmt_df=reference_comment_df)

Found 10 article ids in generated comments and 10 article ids in reference comments
Sentence embedding length> 768


Training epochs:   0%|          | 0/12 [00:00<?, ?it/s]

Running epoch: 1


c:\Users\trothe\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\functional.py:1956: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


Loss for this epoch: 2.231155824661255
Running epoch: 2


Loss for this epoch: 1.9684468746185302
Running epoch: 3


Loss for this epoch: 1.7471392750740051
Running epoch: 4


Training epochs:  33%|███▎      | 4/12 [00:00<00:00, 34.32it/s]

Loss for this epoch: 1.4545078337192536
Running epoch: 5


Loss for this epoch: 1.2492070555686952
Running epoch: 6


Loss for this epoch: 1.1582678437232972
Running epoch: 7


Loss for this epoch: 0.9293346464633941
Running epoch: 8


Training epochs:  67%|██████▋   | 8/12 [00:00<00:00, 34.82it/s]

Loss for this epoch: 0.7824429035186767
Running epoch: 9


Loss for this epoch: 0.6460552513599396
Running epoch: 10


Loss for this epoch: 0.5648240059614181
Running epoch: 11


Loss for this epoch: 0.49724355936050413
Running epoch: 12


Training epochs: 100%|██████████| 12/12 [00:00<00:00, 35.63it/s]


Loss for this epoch: 0.40360480546951294


Evaluation batches: 100%|██████████| 10/10 [00:00<00:00, 2448.37it/s]


Average evaluation loss: 1.4221003636717797
Classification accuracy: 0.4256756901741028
[tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(4, dtype=torch.int32), tensor(8, dtype=torch.int32), tensor(8, dtype=torch.int32), tensor(8, dtype=torch.int32), tensor(8, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, dtype=torch.int32), tensor(2, d

Batches: 100%|██████████| 5/5 [00:00<00:00,  8.01it/s]


SVM accuracy:  0.42567567567567566
======= DONE WITH SBERT CLASSIFICATION ======== 


Batches: 100%|██████████| 1/1 [00:00<00:00, 18.87it/s]


Mean cosine similarity score over all articles:  0.35304898
0.08988763900012627 0.0
0.062499997812500076 0.0
0.11320754546101817 0.06896551595719383
0.0 0.0
0.36363635867768607 0.2222222172839506
0.12121211676767694 0.0
0.1481481432098767 0.0799999950720003
0.0 0.0
0.1126760539178735 0.02247190811766209
0.0645161241623313 0.0
Mean Rouge-1 score over all articles:  0.10757839790090891
Worst Rouge-1 score over all articles:  0.0
Mean Rouge-2 score over all articles:  0.03936596364308068
Worst Rouge-2 score over all articles:  0.0
Found 10 article ids in generated comments and 10 article ids in reference comments


Batches: 100%|██████████| 5/5 [00:00<00:00,  6.16it/s]


0.5608108108108109
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.00      0.00      0.00         4
           2       0.00      0.00      0.00        30
           3       0.44      1.00      0.61        31
           4       0.00      0.00      0.00         9
           5       0.83      1.00      0.91        20
           6       0.00      0.00      0.00         8
           7       0.00      0.00      0.00        10
           8       0.00      0.00      0.00         4
           9       0.47      1.00      0.64        19

    accuracy                           0.56       148
   macro avg       0.27      0.40      0.32       148
weighted avg       0.35      0.56      0.42       148

[[13  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0 30  0  0  0  0  0  0]
 [ 0  0  0 31  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  9]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0  0  

c:\Users\trothe\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\trothe\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\trothe\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

##### Score overview - Comment split - Evaluation Set

In [7]:

from tabulate import tabulate

cmtsplit_scores_combined = [#["Bare Data (complete, no model)", complete_dataset_score_dict["cosine_similarity"], complete_dataset_score_dict["rouge1_score"], complete_dataset_score_dict["rouge2_score"],complete_dataset_score_dict["svm_class_accuracy"]],
                            ["Bare Data (limited, no model)", limited_dataset_score_dict["cosine_similarity"], limited_dataset_score_dict["rouge1_score"], limited_dataset_score_dict["rouge2_score"], limited_dataset_score_dict["svm_class_accuracy"], limited_dataset_score_dict["sbert_class_accuracy"]],
                            ["Godel-v1.1", godel_scores_dict["cosine_similarity"], godel_scores_dict["rouge1_score"], godel_scores_dict["rouge2_score"], godel_scores_dict["svm_class_accuracy"], godel_scores_dict["sbert_class_accuracy"]],
                            ["Davinci-003", gpt4_scores_dict["cosine_similarity"], gpt4_scores_dict["rouge1_score"], gpt4_scores_dict["rouge2_score"], gpt4_scores_dict["svm_class_accuracy"], gpt4_scores_dict["sbert_class_accuracy"]],
                            ["GPT-3.5-turbo", gpt35turbo_scores_dict["cosine_similarity"], gpt35turbo_scores_dict["rouge1_score"], gpt35turbo_scores_dict["rouge2_score"], gpt35turbo_scores_dict["svm_class_accuracy"], gpt35turbo_scores_dict["sbert_class_accuracy"]],
                            ["GPT-4", gpt4_scores_dict["cosine_similarity"], gpt4_scores_dict["rouge1_score"], gpt4_scores_dict["rouge2_score"], gpt4_scores_dict["svm_class_accuracy"], gpt4_scores_dict["sbert_class_accuracy"]],
                            ]
cmtsplit_table_data_kwargs = {"tabular_data": cmtsplit_scores_combined, "headers": ["Model", "Cosine Sim.", "Rouge-1", "Rouge-2", "SVM Classif. Acc.", "SBERT Classif. Acc."]}

cmtsplit_score_table = tabulate(tablefmt="fancy_grid",
                                **cmtsplit_table_data_kwargs
                                )


#Show Output
print("Scores for data split between comments: \n")
print(cmtsplit_score_table)
print("\n In LaTeX, that is: \n")
print(tabulate(tablefmt="latex",
                **cmtsplit_table_data_kwargs
                )) 

Scores for data split between comments: 

╒═══════════════════════════════╤═══════════════╤═══════════╤═══════════╤═════════════════════╤═══════════════════════╕
│ Model                         │   Cosine Sim. │   Rouge-1 │   Rouge-2 │   SVM Classif. Acc. │   SBERT Classif. Acc. │
╞═══════════════════════════════╪═══════════════╪═══════════╪═══════════╪═════════════════════╪═══════════════════════╡
│ Bare Data (limited, no model) │      0.520087 │  0.13315  │ 0.0362402 │            0.581081 │              0.594595 │
├───────────────────────────────┼───────────────┼───────────┼───────────┼─────────────────────┼───────────────────────┤
│ Godel-v1.1                    │      0.353049 │  0.107578 │ 0.039366  │            0.560811 │              0.425676 │
├───────────────────────────────┼───────────────┼───────────┼───────────┼─────────────────────┼───────────────────────┤
│ Davinci-003                   │      0.542646 │  0.121609 │ 0.0335726 │            0.609375 │              0.640625 

To compare the SVM classification accuracy between the human "real" data and the model generated data, consider also the variance in precisions over all classes. (Can be extracted in the classification report for each each further above.). While the human data has an almost randomly fluctuating but centered value for the precision across classes, the precision goes more into the extremes for the models. This subjective observation can be quantified objectively via the variance as a 0.0497361 vs. 0.127289 for human/real data vs. GPT-4.

##### Original (TF-embedding based):

In [8]:
Scores for data split between comments: 

╒════════════════════════════════╤═══════════════╤═══════════╤═══════════╤═════════════════════╕
│ Model                          │   Cosine Sim. │   Rouge-1 │   Rouge-2 │   SVM Classif. Acc. │
╞════════════════════════════════╪═══════════════╪═══════════╪═══════════╪═════════════════════╡
│ Bare Data (complete, no model) │      0.220525 │  0.15256  │ 0.0611136 │            0.228358 │
├────────────────────────────────┼───────────────┼───────────┼───────────┼─────────────────────┤
│ Bare Data (limited, no model)  │      0.200394 │  0.13315  │ 0.0362402 │            0.5      │
├────────────────────────────────┼───────────────┼───────────┼───────────┼─────────────────────┤
│ Godel-v1.1                     │      0.175213 │  0.107578 │ 0.039366  │            0.135135 │
├────────────────────────────────┼───────────────┼───────────┼───────────┼─────────────────────┤
│ Davinci-003                    │      0.151079 │  0.121609 │ 0.0335726 │            0.275    │
├────────────────────────────────┼───────────────┼───────────┼───────────┼─────────────────────┤
│ GPT-3.5-turbo                  │      0.163473 │  0.136076 │ 0.0359086 │            0.265625 │
├────────────────────────────────┼───────────────┼───────────┼───────────┼─────────────────────┤
│ GPT-4                          │      0.151079 │  0.121609 │ 0.0335726 │            0.275    │
╘════════════════════════════════╧═══════════════╧═══════════╧═══════════╧═════════════════════╛

 In LaTeX, that is: 

\begin{tabular}{lrrrr}
\hline
 Model                          &   Cosine Sim. &   Rouge-1 &   Rouge-2 &   SVM Classif. Acc. \\
\hline
 Bare Data (complete, no model) &      0.220525 &  0.15256  & 0.0611136 &            0.228358 \\
 Bare Data (limited, no model)  &      0.200394 &  0.13315  & 0.0362402 &            0.5      \\
 Godel-v1.1                     &      0.175213 &  0.107578 & 0.039366  &            0.135135 \\
 Davinci-003                    &      0.151079 &  0.121609 & 0.0335726 &            0.275    \\
 GPT-3.5-turbo                  &      0.163473 &  0.136076 & 0.0359086 &            0.265625 \\
 GPT-4                          &      0.151079 &  0.121609 & 0.0335726 &            0.275    \\
\hline
\end{tabular}

SyntaxError: invalid character '╒' (U+2552) (Temp/ipykernel_22812/1425709987.py, line 3)